apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langfuse.configMap" . }}
data:
  TELEMETRY_ENABLED: {{ .Values.toggles.telemetry | quote }}
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: {{ .Values.toggles.experimentalFeatures | quote }}
  NEXT_PUBLIC_SIGN_UP_DISABLED: {{ .Values.toggles.disablePublicSignup | quote }}
