{{- if (or .Values.databaseURL .Values.directURL) -}}
  
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.connectionSecret.name" . }}
type: Opaque
data:
  {{- if .Values.databaseURL }}
  database-url: {{ .Values.databaseURL }}
  {{- end }}
  {{- if .Values.directURL }}
  direct-url: {{ .Values.directURL }}
  {{- end }}

{{- end -}}
