{{- if (or (and (not .Values.postgresql.enabled) .Values.databaseURL) .Values.directURL) -}}
  
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.connectionSecret" . }}
type: Opaque
stringData:
  {{- if (and (not .Values.postgresql.enabled) .Values.databaseURL) }}
  database-url: {{ .Values.databaseURL | quote}}
  {{- end }}
  {{- if .Values.directURL }}
  direct-url: {{ .Values.directURL | quote }}
  {{- end }}

{{- end -}}
