apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langfuse.fullname" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langfuse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "langfuse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "langfuse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-postgres
          image: busybox:latest
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_HOST
              value: {{ include "langfuse.databaseHost" . | quote }}
            - name: DATABASE_PORT
              value: "5432"
            {{- else }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "langfuse.connectionSecret" . | quote }}
                  key: database-url
            {{- end }}
          command:
            - sh
            - -c
            - >
              until nc -z -v -w30 
              ${DATABASE_HOST:-$(echo $DATABASE_URL | awk -F[/:] '{print $4}')} 
              ${DATABASE_PORT:-$(echo $DATABASE_URL | awk -F[/:] '{print $5}'):-"5432"} ; do
                echo 'Waiting for Postgres...' ;
                sleep 5 ;
              done
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: DATABASE_NAME
              value: {{ include "langfuse.databaseName" . }}
            - name: DATABASE_HOST
              value: {{ include "langfuse.databaseHost" . }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "langfuse.postgresqlSecret" . }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}
            {{- else }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "langfuse.connectionSecret" . }}
                  key: database-url
            {{- end }}
            {{- if .Values.directURL }}
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "langfuse.connectionSecret" . }}
                  key: direct-url
            {{- end }}
            - name: NEXTAUTH_URL
              value: {{ .Values.nextauthURL }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "langfuse.internalSecret" . }}
                  key: auth-secret
            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: {{ include "langfuse.internalSecret" . }}
                  key: salt
          envFrom:
            - configMapRef:
                name: {{ include "langfuse.configMap" . }}
            {{- include "langfuse.additionalSecrets" . }}
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/public/health
              port: http
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
