{{- if .Values.postgresqlSecret.create -}}
{{- $secretName := (include "langfuse.postgresqlSecret" .) -}}
{{- $secretData := $secretName | lookup "v1" "Secret" .Release.Namespace | dig "data" dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  {{- if .Values.postgresqlSecret.keep }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
type: Opaque
data:
  {{- range (values .Values.postgresql.auth.secretKeys) }}
  {{.}}: {{ get $secretData . | default (randAlphaNum 32 | b64enc) | quote }}
  {{- end -}}

{{- end -}}
