name: Lint Code Base

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: "main"
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_KUBERNETES_KUBECONFORM: false

  lint-generated-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Delete .git
        run: rm -rf .git
      - name: Generate and validate releases
        uses: shivjm/helm-kubeconform-action@v0.2.0
        with:
          chartsDirectory: .
