name: Lint Code Base

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: "main"
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_KUBERNETES_KUBECONFORM: false

  lint-generated-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare a charts folder
        run: |
          mkdir -p charts
          for dir in $(ls -d */); do
              if [[ $dir != charts/ && $dir != .* ]] ; then
                  helm dependency build $dir          
                  mv $dir charts/
              fi
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate and validate releases
        uses: docker://ghcr.io/shivjm/helm-kubeconform-action:v0.2.0
        env:
          CHARTS_DIRECTORY: charts
          HELM_UPDATE_DEPENDENCIES: false
          LOG_LEVEL: trace
          LOG_JSON: false
